### ISSUE TITLE
After despawning, new ParticleEffects don't produce particles

### ISSUE THREAD

**Issue by theon** [djeedai/bevy_hanabi#106]
## Environment

bevy: 0.9
bevy_hanabi: 0.5
OS: MacOS

## Issue

After despawning `ParticleEffect` entities, newly spawned `ParticleEffect` entities don't produce particles 

## Reproducing

See the following code for a reproduction: https://github.com/theon/bevy_hanabi/commit/132ce0b17050067e14c07935a8290a1cdd6b7177

The reproduction code spawns a new ParticleEffect entity every second. Once there are `MAX_EFFECTS` entities it despawns the oldest entity before spawning the next.

Setting `MAX_EFFECTS` in that example seems to determine when the issue starts:
 - MAX_EFFECTS=1, 3rd spawned particle effect doesn't create particles
 - MAX_EFFECTS=2, 4th spawned particle effect doesn't create particles
 - MAX_EFFECTS=10, 12th spawned particle effect doesn't create particles

Example where `MAX_EFFECTS=5` and the 7th spawned entity onwards doesn't produce particles:
https://user-images.githubusercontent.com/759170/209003169-085f376e-8465-41cd-91a8-1649c318d691.mp4

Note: There is no issue when commenting out the line with `despawn_recursive()`

**Comment by djeedai** [comment]
There's 2 bugs here:

- The simple one: some bind group was not re-created, so the new effect was using the bind group of the old effect. Fixed in #107.
- The hard one: the indirect compute pass assumes N effects are allocated as N consecutive GPU particle buffers, but when some effects are deleted and their GPU buffer de-allocated, there may be a gap in the numbering. This was compounded by the fact we were first allocating new effect before we deallocated old ones; this part has been inverted in #107 such that despawning and spawning the same number of effects per frame doesn't produce any bug. But there's no easy fix for the case where for example more effects are despawned than are spawned in the same frame (and not in LIFO order).

**Comment by djeedai** [comment]
Re-opening; this is only partially fixed as explained above.

**Comment by vultix** [comment]
Just ran into this - I'd be happy to help contribute a fix once you know what solution you'd like

**Comment by djeedai** [comment]
Opportunistically closed by #149 as I believe this was the last bug, and everything should be fixed. Please reopen if there's still a case I missed, but RenderDoc shows no error in all cases I looked at. CC: @vultix @theon
