### ISSUE TITLE
All particles reset when a new effect is spawned

### ISSUE THREAD

**Issue by NiseVoid** [djeedai/bevy_hanabi#117]
When spawning a new ParticleEffect, all particles disappear and existing effects will appear as if they had just been created. This effect can be seen in the example of #106. This seems to happen regardless of them using the same effect handle or a different effect.

**Comment by djeedai** [comment]
I modified the `instance.rs` example and I can trivially reproduce that bug. I'll investigate.

**Comment by djeedai** [comment]
I identified the issue, some GPU buffer content is overwritten entirely instead of writing only the row(s) for the new effect(s). This is pretty obvious from the code:

https://github.com/djeedai/bevy_hanabi/blob/368a17bcff98bbba255118874234605e09c5df93/src/render/aligned_buffer_vec.rs#L159

I need a tiny bit of internal clean-up and a new utility to keep track of those and be smarter when writing GPU data. This is conceptually easy to fix but might take a bit to write.

**Comment by djeedai** [comment]
This should be fixed now if anyone wants to try on `main`.
