### ISSUE TITLE
Infinite lifetime particles.

### ISSUE THREAD

**Issue by brandon-reinhart** [djeedai/bevy_hanabi#118]
It's not unusual to want particles with infinite lifetimes and some other criteria for their destruction.

Suggestions:

- separate the destruction criteria and provide configurable DestructionModifiers
- example destruction criteria: particle goes offscreen, particle enters volume, particle exits volume
- remove the requirement that all particles have a bounded lifetime
- adjust age/gradient to loop
- init modifier that is able to set initial particle age (ex: to random value)

**Comment by brandon-reinhart** [comment]
Also, continuous emitters should be configurable to do things like:

- replace oldest particle with new particle
- emit no further particles if emitter count has been reached
- replace random particle with new particle

**Comment by djeedai** [comment]
Yes to all, thanks. This is going to be a lot easier to implement after #109 and any follow up refactor moving into the direction of a VFX graph with basic building blocks. Although the emitter one is probably doable already.

**Comment by djeedai** [comment]
#109 just merged, and this solves a few items:
- effect require an explicit `InitLifetimeModifier`; you can create an effect without and get an unbounded lifetime, although currently you'll get a warning because there's not much you can achieve with this so it's probably an error for most users
- `InitLifetimeModifier::lifetime` now can be a random value, to add more variety
- added `InitAgeModifier` with random value support

**Comment by djeedai** [comment]
Opened separate feature requests for the few remaining items. Closing this issue, as I think everything else is now available.

**Comment by brandon-reinhart** [comment]
Neat! I will check this out.
