### ISSUE TITLE
Text Based Partices

### ISSUE THREAD

**Issue by andrewexton373** [djeedai/bevy_hanabi#159]
Hello,

I'm unsure the feasibility of this idea, but I thought it might be interesting to be able to use bevy_hanabi to render text particles. The main use-case that comes to mind would be for highlighting damage on hits to enemies/players in many games. I'll keep searching around for alternatives to this, but I hadn't seen anything thus far, and didn't see any previous related issues posted. Let me know if there's any additional thoughts on this idea, thanks for the time!

**Comment by djeedai** [comment]
I'm not sure about this. If I understand correctly, you want to use particles to render texts (like, multi-digit numbers) for enemy damage, expecting you'll maybe get a lot of them? I don't think using a particle system is necessarily the best approach, as each "particle" (=text) requires specific information about what to display (I assume you won't display just random values). So that's quite a bit of data to transfer from CPU to GPU, which a GPU particle system like 🎆 Hanabi precisely tries to avoid. I'd personally try instead a solution based on entities and text components first; this should be fast enough since characters are baked into textures anyway. And you're nowhere near the order of magnitude where a particle system shines; I'd expect texts in the order of ~100 characters on screen, while particles are more in the order of 10k~10million. What do you expect a particle system based solution will provide?

**Comment by andrewexton373** [comment]
Understood, I think you're right about using entities and text components as a better approach. I thought it would be cool to be able to have billboard textures generated from provided text (ex: "BLOCK!", "-125HP") that could then be rendered with a particle system for animation purposes. It seems as though the GPU transfer bottleneck for generated billboard textures would introduce feasibility problems, and something I hadn't really considered. I appreciate your time pondering the thought though, thanks for your contributions!

**Comment by djeedai** [comment]
I mean, it's not an unreasonable approach to consider if you're limiting yourself to a predefined set of characters (like digits only for numbers, or uppercase A-Z only) that you pre-baked into a single texture. The cost of transferring some kind of data from CPU to GPU to define the text is always there, whether you use 🎆 Hanabi or something else. And anyway Bevy to render text will do that same texture baking into an atlas. But the architecture of a GPU particle system is generally designed to operate with the least amount of CPU interaction possible for performance reason, so that won't fit well with highly dynamic content controller by CPU. So for something like "BLOCK!" which is always the same, that's fine. For the actual numerical value of damages however that sounds more tricky. So I'd definitely start by using the standard Bevy components, and if there a performance issue (I don't expect there will be) then come back to explore a particle-based solution. Thanks for opening the issue though it was an interesting idea!

**Comment by djeedai** [comment]
@andrewexton373 do you mind if we close this for now? And you can re-open if you find the component-based approach doesn't work and the particle-based one is relevant anyway.

**Comment by andrewexton373** [comment]
Yes, absolutely.
