### ISSUE TITLE
Mutably dereferencing a `Mut<ParticleEffect>` causes an assertion failure

### ISSUE THREAD

**Issue by SludgePhD** [djeedai/bevy_hanabi#228]
**Crate versions**
`bevy` version: 0.11
`bevy_hanabi` version: 0.7

**Describe the bug**

When a `ParticleEffect` component is mutably accessed without changing its effect handle, `bevy_hanabi` panics with an assertion failure:

```
thread 'Compute Task Pool (7)' panicked at 'assertion failed: self.asset != weak_handle', /home/sludge/code/bevy_hanabi/src/lib.rs:1061:9
```

The assertion is this:

```rust
debug_assert!(self.asset != weak_handle);
```

It looks like the assumption is made that any mutable dereference of the `ParticleEffect` will change its effect handle, but that isn't necessarily the case.

**Expected behavior**
No panic should happen. The effect should either be recompiled, or left as-is, if neither the handle nor any other data used by the compilation changed, and bevy_hanabi wants to do more fine-grained change detection here.

**To Reproduce**
This system causes an assertion failure in bevy_hanabi when the `A` key is pressed and any `ParticleEffect`s exist:

```rust
fn boop_effects(mut q: Query<&mut ParticleEffect>, inp: Res<Input<KeyCode>>) {
    if inp.just_pressed(KeyCode::A) {
        for mut effect in &mut q {
            effect.deref_mut();
        }
    }
}
```

**Comment by djeedai** [comment]
This check should have prevented `update()` from being called. This is why there's an assert in place, because `update()` shouldn't be called if the asset handle is not changed. So the bug is not the assert, it's `update()` being called in the first place. Not sure why the check doesn't work.

https://github.com/djeedai/bevy_hanabi/blob/5832bb99dd6881d6041bb2aff7b8a0696c19ab71/src/lib.rs#L1341-L1343

**Comment by djeedai** [comment]
I just removed the assert, let it do a full rebuild. That should work now.
