### ISSUE TITLE
I am a rookie. I have tried 3 times and cleared the cache, but now I am reporting this error. What does this mean?

### ISSUE THREAD

**Issue by lx2720** [djeedai/bevy_hanabi#231]
![3](https://github.com/djeedai/bevy_hanabi/assets/19430019/46d23b86-c45a-4481-a052-5dd5b1a78e6d)
I am a rookie. I have tried 3 times and cleared the cache, but now I am reporting this error. What does this mean?

**Comment by djeedai** [comment]
This code is only available on GitHub. Are you consuming `bevy_hanabi` by pointing `cargo.toml` at the git repository? If so, which commit, and what code generates that error? Otherwise I don't understand how you can get that error from any crates.io released package version because that code was never released.

**Comment by lx2720** [comment]
Okay, thank you. Maybe I should look forward to the next version :)
