### ISSUE TITLE
it would be VERY NICE to be able to pass a BOX to init()

### ISSUE THREAD

**Issue by ethereumdegen** [djeedai/bevy_hanabi#274]
**Describe the solution you'd like**

it would be VERY NICE to be able to pass a BOX to init()

#[inline]
    pub fn init<M>(mut self, modifier: M) -> Self
    where
        M: InitModifier + Send + Sync + 'static,
    {
        self.init_modifiers.push(Box::new(modifier));
        self
    }

**Describe _why_ you want that solution. Is this related to a problem?**
A clear and concise description of what the problem is. Ex.: If I could do [X] then the code would be more concise / easier to read / etc. or I'm blocked in this case to do [Y] because of a limitation of the API

Well first of all, look, the input is just being put into a box right away anyways. However, it has to go in as static and sized which realllly sucks when i am trying to do something cool.  If this were possible, i could send a box that contains ANYTHING that impls modifier ... basically it could be either a  Tangent Velocity Modifier or a Sphere Velocity Modifier and it would help me immensely in my code that is dynamically creating emitters from serialized files

**Comment by ethereumdegen** [comment]
Basically i built this 


https://github.com/ethereumdegen/bevy_hanabi_loader

and I would like to be able to more programatically define rotation and velocity shapes from a file .  

In fact i would love if you read how my crate works (the billboard file code) and thought about how to better apply it to hanabi in general

**Comment by djeedai** [comment]
> it would be VERY NICE to be able to pass a BOX to init()

It shouldn't be a problem to add a boxed variant for advanced users. This just requires some checks to ensure consistency of modifier context.

> Well first of all, look, the input is just being put into a box right away anyways.

This is a common Rust pattern as far as I know. This saves the user from having to write the boxing manually each time.

> However, it has to go in as static and sized which realllly sucks when i am trying to do something cool.

The static bound is required to own the modifier object. Adding a lifetime here would infect all objects, and would probably not work with Bevy anyway. Also `Box<dyn Trait + 'a>` in general is an anti-pattern; the boxing is often here precisely to avoid the lifetime bound. Otherwise I'd just use `&'a dyn Trait` without boxing.

https://users.rust-lang.org/t/box-with-a-trait-object-requires-static-lifetime/35261

The `Sized` bound is almost mandatory with `Box`, you would need unsafe code to create a `Box<!Sized>`.

https://stackoverflow.com/questions/39216874/how-do-you-create-a-boxdyn-trait-or-a-boxed-unsized-value-in-general#39221425
