### ISSUE TITLE
Particles always render facing along the X-axis

### ISSUE THREAD

**Issue by MathiasPius** [djeedai/bevy_hanabi#38]
Not sure if this qualifies as an issue, but I'm not sure how to get the particle system to work the way I'd like it to, and I'd really appreciate some help if you can spare the time :)

I'm using Bevy 0.8.0 and Hanabi 0.3.0 to simulate space dust in a 3D game, but the particles always render facing down the X-axis, and I'm not sure how to go about correcting them. I assumed the particles would always face the camera, but that doesn't appear to be the case.

When viewing the particle effect cluster from along the X-axis, it looks perfect:
![Screenshot from 2022-08-11 10-46-46](https://user-images.githubusercontent.com/769916/184099408-21e5293c-b0e8-41b1-adf4-972022f3dca5.png)

When viewing from the Z-axis, the particles are barely visible, because they're perpendicular to the viewing angle:
![Screenshot from 2022-08-11 10-49-06](https://user-images.githubusercontent.com/769916/184099589-c51d932c-a01c-4582-835a-c369f3123e9d.png)

I initially just tried to create two perpendicular particle effects to circumvent the issue, but the rotation component of the transform is also ignored by the renderer, which makes sense in hindsight, but I had to try :)

The code that I'm using to create the clouds is [here](https://github.com/Bromidity/star-lost/blob/05d19657044fee5b396ae54a9d4947e117f51da6/src/dust.rs)
My camera definition, which I suspect might be relevant is defined [here](https://github.com/Bromidity/star-lost/blob/05d19657044fee5b396ae54a9d4947e117f51da6/src/tests/controls.rs#L31-L35). I'm parenting it to a "Ship" entity, which I suspect might be relevant.

Anyway, thanks for creating this plugin, even with this issue, the particle system is amazing and helped me get over a mental block!

**Comment by djeedai** [comment]
Yes, that's a limitation currently, simply because nobody went and wrote the proper piece of code to align the particles. I appreciate that makes the crate quite unusable in "full 3D", I'm much sorry about that. This is actually indirectly called out in the README, you can see that "Face camera" and "Face constant direction" are both unchecked; there's simply no code to orient the particle today. That being said that shouldn't be too hard to fix if you want to give it a try, you'd have to bind the camera view uniforms of Bevy to recover the camera position, and add an `UpdateModifier` (or hardcode in your branch) to toggle the behavior. I'll see if I can find some time this week to fix it.

**Comment by MathiasPius** [comment]
Thank you! My shader skills are a little rusty, but I'm gonna see if I can figure it out. Your pointers have so far been super helpful in orienting myself in the codebase and have a semi-working hardcoded shader already so hopefully I can spare you the trouble :)

I'll open a pull request once I have something worthwhile.
