### ISSUE TITLE
Panic when spawners are removed quickly

### ISSUE THREAD

**Issue by auderer** [djeedai/bevy_hanabi#60]
I'm currently inserting a ParticleEffectBundle on every bullet in my game to create a trail of particles. When I despawn the bullets on collision, I occasionally get the following panic:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/render/mod.rs:1963:30
```

It seems like it might be a race condition regarding the bind groups.

Reproducible on my fork in the `spawner-removal` branch, in the `remove.rs` example: https://github.com/auderer/bevy_hanabi/blob/spawner-removal/examples/remove.rs

In my example, if you hold down the left mouse button to spam spawners, they will eventually panic while being removed.

**Comment by djeedai** [comment]
I'm not sure why this would happen. The bind group hash map is populated during the queue render phase, and used during the actual compute and rendering. Those all happen while the Render App is rendering a same frame, so cannot happen in parallel, unless multiple frames are being rendered in parallel which shouldn't happen I think. I'll try to repro and have a look but this looks weird.

**Comment by darthdeus** [comment]
This happens to me too after upgrading to `0.4.0`. It did not happen on `0.3.1`, but that also had the bug of not removing particle systems when the entity is despawned (#45 and #61).

I'd assume the reason it didn't happen to me before is because the particle systems never got removed, but once I upgraded to `0.4.0` they now get properly removed, and if I cause them to be removed immediately as they're spawned the game crashes.
