### ISSUE TITLE
Support RenderLayers and multi-camera rendering

### ISSUE THREAD

**Issue by malleusinferni** [djeedai/bevy_hanabi#71]
The stock Bevy render pipeline allows cameras with the [RenderLayers](https://docs.rs/bevy_render/0.8.1/bevy_render/view/visibility/struct.RenderLayers.html) component to ignore entities without a matching layer mask (encoded with the same RenderLayers component). This allows multiple cameras to be used to construct a wide range of visual effects.

Particles currently render on all cameras, ignoring the RenderLayers component. This can result in conflicts between effects that use particles and effects that use multiple cameras. To support this Bevy feature, the particle rendering pipeline must detect the RenderLayers component on camera entities and allow layer-specific emitters or effect assets.

**Comment by djeedai** [comment]
I looked at `RenderLayers` and as I understand it a render pipeline shouldn't really care about this, but rather about the per-view `VisibleEntities`, which admittedly we also ignore currently. This is because the combination of the render layers of entities vs. the render layers of cameras are baked into `VisibleEntities` already, alongside the per-entity `Visibility`. But respecting `VisibleEntities` in Hanabi requires a tiny bit of refactor because:

- for particle spawning and update, this is view-independent, and we can aggressively batch compatible effects together, which is what we do now (more or less; there's room for improvement).
- for rendering, sorting (not implemented), and some related effects like billboarding, this is view-dependent and the current batching doesn't work anymore, we need to do a separate per-view batching.

**Comment by djeedai** [comment]
See the new `multicam` example for multiple viewports/cameras and render layers support.
