### ISSUE TITLE
Panic when referencing a buffer with no value

### ISSUE THREAD

**Issue by marshauf** [djeedai/bevy_hanabi#9]
Hello,

my application panics at
`
thread 'TaskPool (10)' panicked at 'called `Option::unwrap()` on a `None` value', /home/marcel/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_hanabi-0.1.1/src/render/mod.rs:1173:62
`
I can't pinpoint/reproduce what is causing the panic, at the moment. I suspect it is some race between calling prepare_effects and queue_effects.
Could you please help me debug the issue.

**Comment by djeedai** [comment]
For reference, the code failing is here:

https://github.com/djeedai/bevy_hanabi/blob/3f42665c9fa06f36130345c90b598ca63a2ab74e/src/render/mod.rs#L1173

If you had a repro that would be awesome, because I've never observed something like that. I can see that a race condition would break things possibly, but the entire Bevy render design seems brittle if that's the case. On the other hand the "prepare"  and "queue" phases are loosely defined as far as I can tell, and I'm still not very sure why the render world uses static lifetimes (those `SQuery` _etc._) so it's possible indeed that we use a buffer for rendering during the previous frame while the next frame "prepare" tries to modify it.

Were you deleting a `ParticleEffect` by any chance?

**Comment by marshauf** [comment]
I found the root cause. When you add bevy_hanabi plugin without adding any ParticleEffect it panics. Adding an effect solves the issue.

**Comment by djeedai** [comment]
Actually, I've used the `gradient` example and commented out the `commands.spawn()` block. And nothing panics. I then commented out also the `effects.add()` call, and still no panic. Not sure why it panics for you. Tested on latest `dev` @ deedd20b9bc84dedd14b873bad2823095f1a3313.

**Comment by marshauf** [comment]
Yes, it is fixed in the main branch.
It seems to be a problem in version 0.1.1.

**Comment by djeedai** [comment]
I plan to make a new release shortly, I was waiting for the force field PR to merge. Thanks for your patience!
